name: Testing - Reusable Workflow
on: 
  workflow_call:
    inputs:
      ingress_url:
        description: The url for the ingress
        required: true
        type: string

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The ingress URL is: ${{ inputs.ingress_url }}"
